import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Yoshida Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav></nav>
      <header>
        <div className="p-2 md:flex justify-between">
          <div className="text-center">
            <Image
              src="/images/logo.png"
              width={120}
              height={60}
              // layout="fill"
              objectFit="contain"
            />
          </div>
          <div className="my-auto flex justify-center text-[#008c8d] text-sm md:text-base font-medium">
            <a href="" className="mx-2 md:mx-4">
              ABOUT
            </a>
            <a href="" className="mx-2 md:mx-4">
              SKILLS
            </a>
            <a href="" className="mx-2 md:mx-4">
              VALUES
            </a>
            <a href="" className="mx-2 md:mx-4">
              FUTURE
            </a>
          </div>
        </div>
      </header>
      <main>
        <section className="bg-[#6bc2c3]">
          <div className="p-5 text-center md:flex justify-between">
            <div className="md:my-auto md:ml-20 md:text-left">
              <h1 className="tracking-widest font-bold text-2xl md:text-4xl text-white">
                メインタイトル
              </h1>
              <p className="tracking-widest my-3 text-base md:text-2xl text-white">
                サブタイトル
              </p>
            </div>
            <div className="px-10 md:p-10 md:text-right">
              <Image
                src="/images/hero.png"
                alt="hero"
                width={585}
                height={498}
              />
            </div>
          </div>
        </section>
        <section className="md:py-10 w-full bg-cover bg-about">
          <div className="mx-auto text-center py-6 md:flex justify-center">
            <p className="text-xl md:text-3xl font-bold tracking-widest">
              私について
            </p>
            <p className="text-sm md:text-base pl-2 text-[#008c8d] md:flex items-center">
              ABOUT
            </p>
          </div>
          <div className="mx-auto max-w-screen-lg md:flex justify-center">
            <div className="mx-auto w-[320px] p-5">
              <div className="text-center">
                <Image
                  src="/images/about-1.png"
                  width={184}
                  height={157}
                  // layout="fill"
                  objectFit="contain"
                />
              </div>
              <p className="text-[#008c8d] font-bold text-xl md:text-2xl text-center my-1 md:my-3">
                趣味
              </p>
              <p className="leading-7">
                つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。
              </p>
            </div>
            <div className="mx-auto w-[320px] p-5">
              <div className="text-center">
                <Image
                  src="/images/about-2.png"
                  width={184}
                  height={157}
                  // layout="fill"
                  objectFit="contain"
                />
              </div>
              <p className="text-[#008c8d] font-bold text-xl md:text-2xl text-center my-1 md:my-3">
                趣味
              </p>
              <p className="leading-7">
                つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて
              </p>
            </div>
            <div className="mx-auto w-[320px] p-5">
              <div className="text-center">
                <Image
                  src="/images/about-3.png"
                  width={184}
                  height={157}
                  // layout="fill"
                  objectFit="contain"
                />
              </div>
              <p className="text-[#008c8d] font-bold text-xl md:text-2xl text-center my-1 md:my-3">
                趣味
              </p>
              <p className="leading-7">
                つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。
              </p>
            </div>
          </div>
        </section>
        <section className="md:py-10 w-full bg-cover bg-skills">
          <div className=" max-w-screen-lg mx-auto md:flex justify-center">
            <div className="px-10 md:p-10">
              <div className="md:hidden mx-auto text-center py-4">
                <p className="text-xl md:text-3xl font-bold tracking-widest">
                  スキル
                </p>
                <p className="text-sm md:text-base font-semibold pl-2 text-[#008c8d] md:flex items-center">
                  SKILLS
                </p>
              </div>
              <Image
                src="/images/skill.png"
                alt="skill"
                width={535}
                height={372}
              />
            </div>
            <div>
              <div className="mx-auto md:max-w-[640px] p-5">
                <div className="hidden mx-auto text-center py-4 md:flex justify-start">
                  <p className="text-xl md:text-3xl font-bold tracking-widest">
                    スキル
                  </p>
                  <p className="text-sm md:text-base font-semibold pl-2 text-[#008c8d] md:flex items-center">
                    SKILLS
                  </p>
                </div>
                <p className="text-sm md:text-base leading-7">
                  つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて心にうつりゆくよしなし事をそこはかとなく書きつくれば、あやしうこそものぐるほしけれ。つれづれなるまゝに日暮らし硯にむかひて。
                </p>
                <div className="mt-4 rounded p-4 md:p-8 bg-white">
                  <div className="mt-2 first:mt-0">
                    <p className="tracking-wider text-sm md:text-base font-semibold text-[#008c8d] opacity-80">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="w-11/12 mr-4">
                        <div className="relative pt-1">
                          <div className="overflow-hidden h-4 text-xs flex rounded bg-[#c5eaea]">
                            <div
                              style={{ width: "40%" }}
                              className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-[#2bb9ba]"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-[#008c8d]">40%</li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="tracking-wider text-sm md:text-base font-semibold text-[#008c8d] opacity-80">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="w-11/12 mr-4">
                        <div className="relative pt-1">
                          <div className="overflow-hidden h-4 text-xs flex rounded bg-[#c5eaea]">
                            <div
                              style={{ width: "40%" }}
                              className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-[#2bb9ba]"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-[#008c8d]">40%</li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="tracking-wider text-sm md:text-base font-semibold text-[#008c8d] opacity-80">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="w-11/12 mr-4">
                        <div className="relative pt-1">
                          <div className="overflow-hidden h-4 text-xs flex rounded bg-[#c5eaea]">
                            <div
                              style={{ width: "40%" }}
                              className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-[#2bb9ba]"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-[#008c8d]">40%</li>
                    </ul>
                  </div>
                  <div className="mt-2 first:mt-0">
                    <p className="tracking-wider text-sm md:text-base font-semibold text-[#008c8d] opacity-80">
                      SKILLSKILL
                    </p>
                    <ul className="flex">
                      <li className="w-11/12 mr-4">
                        <div className="relative pt-1">
                          <div className="overflow-hidden h-4 text-xs flex rounded bg-[#c5eaea]">
                            <div
                              style={{ width: "40%" }}
                              className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-[#2bb9ba]"
                            ></div>
                          </div>
                        </div>
                      </li>
                      <li className="w-1/12 text-[#008c8d]">40%</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="h-64 bg-slate-200">aaaa</section>
        <section className="h-64 w-full bg-cover bg-future"></section>
      </main>
      <footer className="h-64 bg-[#262c3a] text-white">
        <p>ここがフッター</p>
      </footer>
    </>
  );
}
